/** Declaration file generated by dts-gen */
/* tslint:disable */

export = espower_loader;

declare interface IEspowerLoaderOpt {
    cwd?: string;
    pattern: string;
    espowerOptions: {
        patterns: string[];
    };
}

declare function espower_loader(options: IEspowerLoaderOpt): void;

declare namespace espower_loader {
    const prototype: {
    };

}
